### ISSUE TITLE
OG タグを設定しよう！

### ISSUE THREAD

**Issue by hgw** [nukemenukeme/bedroom02#3]
`<head>〜</head>` 間に OG タグの追加をおねがいしますー。とりあえず以下の様なかんじで。

``` html
  <meta property="og:title" content="The Internet Bedroom presented by IDPW">
  <meta property="og:type" content="website">
  <meta property="og:url" content="http://idpw.org/bedroom/000002/">
  <meta property="og:image" content="http://idpw.org/000002/画像の名前.jpg">
  <meta property="og:description" content="Let’s have a sleepover on the internet! The bedroom performance runs 24 hours from June 23rd - 24th, 2016 on Google Hangout Video Chat System.">
```

**Comment by nukemenukeme** [comment]
OGタグ、追加しました！

**Comment by hgw** [comment]
@nukemenukeme 💮 💮 💮  ありがとうー！

1点だけ！
`画像の名前` のところ、なにか適当に OG (Facebook などにシェアされた時に表示される) 画像を用意して登録しておいてもらえる？ 1200px × 630px などで。
https://github.com/nukemenukeme/bedroom02/blob/gh-pages/index.html#L9 

`index.html` と同じディレクトリに画像も入れてもらえれば OK です！
お手数おかけします 🙏 

http://ogimage.tsmallfield.com/

**Comment by nukemenukeme** [comment]
OG画像、同じディレクトリ内に追加してリンク貼っておきました！
