### ISSUE TITLE
テキストの読みやすさ

### ISSUE THREAD

**Issue by sembo** [nukemenukeme/bedroom02#4]
ディスクリプションがでかすぎて読みにくいね〜
タイトルとかはいいと思うけど、読ませるところは読みやすくしよう

**Comment by nukemenukeme** [comment]
読みやすくしたいです！

**Comment by hgw** [comment]
@nukemenukeme @sembo 

`font-size` と `letter-spacing` を調整しました。
そして月と太陽をたしてみました。具象的すぎてポエティックじゃない、ということでしたらはずしてもいいですよ。

@nukemenukeme 
次、編集するときは `git pull` (GitHub アプリなら Sync?) してくださいー。

http://nukemenukeme.github.io/bedroom02/

**Comment by nukemenukeme** [comment]
ありがとうございます！かわいい！良いと思います～
