### ISSUE TITLE
font detector bug

### ISSUE THREAD

**Issue by yusukeshib** [nukemenukeme/bedroom02#8]
fontが入っていなくてもtrueをかえしてるので、windingsの入ってないPCで文字化け。
https://github.com/nukemenukeme/bedroom02/blob/gh-pages/js/main.js#L30

**Comment by hgw** [comment]
がーん、まじですか。ご報告ありがとうございます。なんとかします。

**Comment by hgw** [comment]
@yusukeshibata 

ちなみにOS / ブラウザの環境教えていただけますか？ 手元の Mac だと `false` が返ってきちゃいました。

**Comment by yusukeshib** [comment]
@hgw 
Mac OS 10.11.5 (15F34)
Chrome Version 50.0.2661.102 (64-bit)

だよ。今気づいたけどWindingsは入ってるね。
![screen shot 2016-06-03 at 10 08 53 pm](https://cloud.githubusercontent.com/assets/127269/15779580/154db364-29d8-11e6-8f72-da97326de5d9.png)
![screen shot 2016-06-03 at 10 10 40 pm](https://cloud.githubusercontent.com/assets/127269/15779589/1a40850e-29d8-11e6-931f-83821b3c4a84.png)

**Comment by hgw** [comment]
@yusukeshibata 
おお、手元の環境だと `OS10.11` `OS10.10` `Chrome 51.0.2704.79` で表示されちゃいますね。なぜだろう。

``` css
font-family: Wingdings;
```

でいけるかと思ったんですが、もうちょっと調べてみますー。

**Comment by yusukeshib** [comment]
Microsoft office for mac.とかを入れてるとかじゃない？
Mac標準のwingdingsは時計マーク入ってないんじゃないかなぁ。

**Comment by hgw** [comment]
> Microsoft office for mac.とかを入れてるとかじゃない？

あぁ、なるほど、あるかもですー。 `Wingdings` と unicode 絵文字を共演させたかったですが、いったん外しますー。

**Comment by hgw** [comment]
Mac では Emoji を優先させるように調整しましたー。不具合あるようだったらまたお知らせください。
